name: magma-access-gateway
base: core20
version: '1.8.0'
summary: Magma's core network
description: Magma's core network

grade: devel
confinement: devmode

parts:

  folly-deps:
    plugin: nil
    build-packages:
      - libgoogle-glog-dev
      - libgflags-dev
      - libboost-all-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libboost-chrono-dev
      - libiberty-dev

  libtins-deps:
    plugin: nil
    build-packages:
      - libpcap-dev=1.9.1-3
      - libmnl-dev=1.0.4-2

  magma-deps:
    plugin: nil
    build-packages:
      - wget
      - software-properties-common
    override-build: |
      set -x
      wget -qO - https://artifactory.magmacore.org:443/artifactory/api/gpg/key/public | apt-key add -
      add-apt-repository 'deb https://artifactory.magmacore.org/artifactory/debian-test focal-ci main'
      add-apt-repository 'deb https://artifactory.magmacore.org/artifactory/debian-test focal-1.7.0 main'
      apt-get update -y
      apt-get install -y bcc-tools libfolly-dev liblfds710 oai-asn1c oai-gnutls oai-nettle oai-freediameter

  bazel:
    plugin: nil
    build-packages:
      - wget
    override-build: |
      set -x
      wget --progress=dot:giga https://github.com/bazelbuild/bazelisk/releases/download/v1.10.0/bazelisk-linux-amd64
      chmod +x bazelisk-linux-amd64
      mv bazelisk-linux-amd64 /usr/sbin/
      ln -f -s /usr/sbin/bazelisk-linux-amd64 /usr/sbin/bazel

  magma-access-gateway:
    plugin: nil
    after:
      - bazel
      - folly-deps
      - libtins-deps
      - magma-deps
    source: https://github.com/magma/magma
    source-type: git
    build-packages:
      - apt-transport-https
      - apt-utils
      - bison
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - gcc
      - gnupg2
      - g++
      - iproute2
      - iputils-ping
      - flex
      - libconfig-dev
      - libcurl4-openssl-dev
      - libczmq-dev
      - libgcrypt-dev
      - libgmp3-dev
      - libidn11-dev
      - libsctp1
      - libsqlite3-dev
      - libsctp-dev
      - libssl-dev
      - libsystemd-dev
      - lld
      - net-tools
      - netbase
      - python3.8
      - python-is-python3
      - python3-distutils
      - systemd
      - uuid-dev
      - vim
      - libtool=2.4.6-14
    override-build: |
      set -x
      mkdir -p /workspaces/magma /etc/magma/
      cp -r . /workspaces/magma/
      cp -r lte/gateway/configs /etc/magma/
      ln -f -s /workspaces/magma/.bazel-cache /var/cache/bazel-cache
      ln -f -s /workspaces/magma/.bazel-cache-repo /var/cache/bazel-cache-repo
      
      bazel build //lte/gateway/release:magma_deb_pkg

      
      ls -a /workspaces/magma/bazel-bin/lte/gateway/release/
